version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    ports:
      - 3000:3000
    restart: always
    networks:
      - compose_network

networks:
  compose_network:
    external: true
