services:
  frontend:
    image: frontend:v1
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - placement
      - redis

  frontend-dapr:
    image: 'daprio/daprd:edge'
    command:
      [
        './daprd',
        '-app-id',
        'frontend',
        '-app-port',
        '3000',
        '-placement-host-address',
        'placement:50006',
        '-components-path',
        '/components',
      ]
    volumes:
      - './components/:/components'
    depends_on:
      - frontend
    network_mode: 'service:frontend'

  percentage:
    image: percentage:v1
    build:
      context: ./backend/percentage-service
    expose:
      - '3001'
    depends_on:
      - placement

  percentage-dapr:
    image: 'daprio/daprd:edge'
    command:
      [
        './daprd',
        '-app-id',
        'percentage',
        '-app-port',
        '3001',
        '-placement-host-address',
        'placement:50006',
        '-components-path',
        '/components',
      ]
    volumes:
      - './components/:/components'
    depends_on:
      - percentage
    network_mode: 'service:percentage'

  placement:
    image: 'daprio/dapr'
    command: ['./placement', '-port', '50006']
    ports:
      - '50006:50006'

  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  redis:
